<?php

namespace App\Repository\Amap;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneContratRepository extends \Doctrine\ORM\EntityRepository
{
}
