<?php

namespace AppBundle\Repository\Amap;

/**
 * PersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonneRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAll()
	{
		return $this->findBy(array(), array('nom' => 'ASC', 'prenom' => 'ASC'));
	}
	public function findById() {
		return $this->findBy(array(), array('id' => 'ASC'));
	}
}
